### ISSUE TITLE
Rename to zDoom

### ISSUE THREAD

**Issue by oldmud0** [caleb1997/DOOM-port-to-the-CE#1]
No, you will not be pushing to `DOOM-port-to-the-CE`. I assure you that.

**Comment by ryanstrades** [comment]
Why zDoom? And what do you mean by "not be pushing to 'DOOM-port-to-the-CE'"?

**Comment by oldmud0** [comment]
It's a ridiculously long name for a repository. Two stop words.

**Comment by ryanstrades** [comment]
Alright, :P
